name: PR Security Checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:

  dependency-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Dependencies for Vulnerabilities
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
